import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Deterministic UUIDs for seed data
const IDS = {
  // Categories
  CAT_CAKES: '10000000-0000-4000-a000-000000000001',
  CAT_PASTRIES: '10000000-0000-4000-a000-000000000002',
  CAT_COOKIES: '10000000-0000-4000-a000-000000000003',
  CAT_ECLAIRS: '10000000-0000-4000-a000-000000000004',
  CAT_DRINKS: '10000000-0000-4000-a000-000000000005',
  CAT_ICE_CREAM: '10000000-0000-4000-a000-000000000006',
  // Products - Cakes
  PROD_NAPOLEON: '20000000-0000-4000-a000-000000000001',
  PROD_MEDOVIK: '20000000-0000-4000-a000-000000000002',
  PROD_PRAGUE: '20000000-0000-4000-a000-000000000003',
  PROD_RED_VELVET: '20000000-0000-4000-a000-000000000004',
  PROD_SMETANNIK: '20000000-0000-4000-a000-000000000005',
  PROD_BIRD_MILK: '20000000-0000-4000-a000-000000000006',
  // Products - Pastries
  PROD_TIRAMISU: '20000000-0000-4000-a000-000000000010',
  PROD_CHEESECAKE: '20000000-0000-4000-a000-000000000011',
  PROD_PROFITEROLE: '20000000-0000-4000-a000-000000000012',
  PROD_PANNA_COTTA: '20000000-0000-4000-a000-000000000013',
  PROD_BROWNIE: '20000000-0000-4000-a000-000000000014',
  // Products - Cookies
  PROD_MACARON: '20000000-0000-4000-a000-000000000020',
  PROD_OATMEAL: '20000000-0000-4000-a000-000000000021',
  PROD_CHOCOLATE_COOKIE: '20000000-0000-4000-a000-000000000022',
  PROD_SHORTBREAD: '20000000-0000-4000-a000-000000000023',
  // Products - Eclairs
  PROD_ECLAIR_CHOCO: '20000000-0000-4000-a000-000000000030',
  PROD_ECLAIR_VANILLA: '20000000-0000-4000-a000-000000000031',
  PROD_ECLAIR_CARAMEL: '20000000-0000-4000-a000-000000000032',
  PROD_ECLAIR_PISTACHIO: '20000000-0000-4000-a000-000000000033',
  // Products - Drinks
  PROD_LATTE: '20000000-0000-4000-a000-000000000040',
  PROD_CAPPUCCINO: '20000000-0000-4000-a000-000000000041',
  PROD_HOT_CHOCOLATE: '20000000-0000-4000-a000-000000000042',
  PROD_TEA: '20000000-0000-4000-a000-000000000043',
  PROD_LEMONADE: '20000000-0000-4000-a000-000000000044',
  // Products - Ice Cream
  PROD_ICE_VANILLA: '20000000-0000-4000-a000-000000000050',
  PROD_ICE_CHOCOLATE: '20000000-0000-4000-a000-000000000051',
  PROD_ICE_STRAWBERRY: '20000000-0000-4000-a000-000000000052',
  PROD_ICE_PISTACHIO: '20000000-0000-4000-a000-000000000053',
  // Stores
  STORE_MAIN: '30000000-0000-4000-a000-000000000001',
  STORE_SOUTH: '30000000-0000-4000-a000-000000000002',
  STORE_WEST: '30000000-0000-4000-a000-000000000003',
  // Promotions
  PROMO_WELCOME: '40000000-0000-4000-a000-000000000001',
  PROMO_CASHBACK: '40000000-0000-4000-a000-000000000002',
  PROMO_COMBO: '40000000-0000-4000-a000-000000000003',
  // Raffle
  RAFFLE_CAKE: '50000000-0000-4000-a000-000000000001',
};

async function main() {
  console.log('Seeding database...');

  // Create settings
  await prisma.settings.createMany({
    data: [
      { key: 'loyalty_cashback_percent', value: '5', description: 'Процент начисления баллов' },
      { key: 'loyalty_max_points_use_percent', value: '50', description: 'Макс. процент оплаты баллами' },
      { key: 'loyalty_point_value', value: '1', description: 'Стоимость 1 балла в сомах' },
      { key: 'delivery_fee', value: '150', description: 'Стоимость доставки (сом)' },
      { key: 'free_delivery_min_amount', value: '2000', description: 'Мин. сумма для бесплатной доставки' },
      { key: 'min_order_amount', value: '500', description: 'Минимальная сумма заказа' },
      { key: 'support_phone', value: '+996701039009', description: 'Телефон поддержки' },
      { key: 'support_email', value: 'support@shirin.kg', description: 'Email поддержки' },
      { key: 'work_hours', value: '09:00-21:00', description: 'Часы работы' },
    ],
    skipDuplicates: true,
  });
  console.log('Settings created');

  // Create admin & test users
  const admin = await prisma.user.upsert({
    where: { phone: '+996700000000' },
    update: {},
    create: {
      phone: '+996700000000',
      firstName: 'Админ',
      lastName: 'Ширин',
      role: 'ADMIN',
      loyaltyPoints: 0,
    },
  });

  const testUser = await prisma.user.upsert({
    where: { phone: '+996700111111' },
    update: {},
    create: {
      phone: '+996700111111',
      firstName: 'Айгуль',
      lastName: 'Тестова',
      role: 'CLIENT',
      loyaltyPoints: 1500,
    },
  });
  console.log('Users created:', admin.phone, testUser.phone);

  // Create categories
  await Promise.all([
    prisma.category.upsert({
      where: { id: IDS.CAT_CAKES },
      update: {},
      create: {
        id: IDS.CAT_CAKES,
        name: 'Торты',
        nameRu: 'Торты',
        nameKy: 'Торттор',
        description: 'Авторские торты на любой праздник',
        icon: 'cake',
        sortOrder: 1,
      },
    }),
    prisma.category.upsert({
      where: { id: IDS.CAT_PASTRIES },
      update: {},
      create: {
        id: IDS.CAT_PASTRIES,
        name: 'Пирожные',
        nameRu: 'Пирожные',
        nameKy: 'Пирожныйлар',
        description: 'Нежные пирожные и десерты',
        icon: 'cupcake',
        sortOrder: 2,
      },
    }),
    prisma.category.upsert({
      where: { id: IDS.CAT_COOKIES },
      update: {},
      create: {
        id: IDS.CAT_COOKIES,
        name: 'Печенье',
        nameRu: 'Печенье',
        nameKy: 'Печенье',
        description: 'Хрустящее печенье ручной работы',
        icon: 'cookie',
        sortOrder: 3,
      },
    }),
    prisma.category.upsert({
      where: { id: IDS.CAT_ECLAIRS },
      update: {},
      create: {
        id: IDS.CAT_ECLAIRS,
        name: 'Эклеры',
        nameRu: 'Эклеры',
        nameKy: 'Эклерлер',
        description: 'Французские эклеры с разными начинками',
        icon: 'eclair',
        sortOrder: 4,
      },
    }),
    prisma.category.upsert({
      where: { id: IDS.CAT_DRINKS },
      update: {},
      create: {
        id: IDS.CAT_DRINKS,
        name: 'Напитки',
        nameRu: 'Напитки',
        nameKy: 'Суусундуктар',
        description: 'Горячие и холодные напитки',
        icon: 'coffee',
        sortOrder: 5,
      },
    }),
    prisma.category.upsert({
      where: { id: IDS.CAT_ICE_CREAM },
      update: {},
      create: {
        id: IDS.CAT_ICE_CREAM,
        name: 'Мороженое',
        nameRu: 'Мороженое',
        nameKy: 'Балмуздак',
        description: 'Домашнее мороженое',
        icon: 'icecream',
        sortOrder: 6,
      },
    }),
  ]);
  console.log('Categories created: 6');

  // Create products - Cakes
  await Promise.all([
    prisma.product.upsert({
      where: { id: IDS.PROD_NAPOLEON },
      update: {},
      create: {
        id: IDS.PROD_NAPOLEON,
        name: 'Наполеон',
        nameRu: 'Наполеон',
        nameKy: 'Наполеон',
        description: 'Классический торт с нежными слоёными коржами и заварным кремом',
        descriptionRu: 'Классический торт с нежными слоёными коржами и заварным кремом',
        descriptionKy: 'Назик катмар корждор жана заварной крем менен классикалык торт',
        price: 1200,
        images: ['https://images.unsplash.com/photo-1568827999250-50f2d0f86352?w=400'],
        ingredients: 'Мука, масло сливочное, яйца, молоко, сахар, ванилин',
        weight: 1000,
        calories: 350,
        categoryId: IDS.CAT_CAKES,
        isBestseller: true,
        sortOrder: 1,
      },
    }),
    prisma.product.upsert({
      where: { id: IDS.PROD_MEDOVIK },
      update: {},
      create: {
        id: IDS.PROD_MEDOVIK,
        name: 'Медовик',
        nameRu: 'Медовик',
        nameKy: 'Бал торт',
        description: 'Медовые коржи со сметанным кремом',
        descriptionRu: 'Медовые коржи со сметанным кремом',
        descriptionKy: 'Бал корждор каймак крем менен',
        price: 1100,
        images: ['https://images.unsplash.com/photo-1621303837174-89787a7d4729?w=400'],
        ingredients: 'Мёд, мука, яйца, сметана, сахар, масло',
        weight: 1000,
        calories: 320,
        categoryId: IDS.CAT_CAKES,
        isNew: true,
        sortOrder: 2,
      },
    }),
    prisma.product.upsert({
      where: { id: IDS.PROD_PRAGUE },
      update: {},
      create: {
        id: IDS.PROD_PRAGUE,
        name: 'Прага',
        nameRu: 'Прага',
        nameKy: 'Прага',
        description: 'Шоколадный торт с шоколадным кремом и глазурью',
        descriptionRu: 'Шоколадный торт с шоколадным кремом и глазурью',
        descriptionKy: 'Шоколад торт шоколад крем жана глазурь менен',
        price: 1300,
        discountPrice: 1100,
        images: ['https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400'],
        ingredients: 'Шоколад, мука, какао, яйца, масло, сахар',
        weight: 1000,
        calories: 380,
        categoryId: IDS.CAT_CAKES,
        sortOrder: 3,
      },
    }),
    prisma.product.upsert({
      where: { id: IDS.PROD_RED_VELVET },
      update: {},
      create: {
        id: IDS.PROD_RED_VELVET,
        name: 'Красный бархат',
        nameRu: 'Красный бархат',
        nameKy: 'Кызыл бархат',
        description: 'Нежный бисквит с крем-чизом',
        descriptionRu: 'Нежный бисквит с крем-чизом',
        descriptionKy: 'Назик бисквит крем-чиз менен',
        price: 1400,
        images: ['https://images.unsplash.com/photo-1616541823729-00fe0aacd32c?w=400'],
        ingredients: 'Мука, какао, сливочный сыр, масло, сахар, яйца',
        weight: 1000,
        calories: 340,
        categoryId: IDS.CAT_CAKES,
        isBestseller: true,
        sortOrder: 4,
      },
    }),
    prisma.product.upsert({
      where: { id: IDS.PROD_SMETANNIK },
      update: {},
      create: {
        id: IDS.PROD_SMETANNIK,
        name: 'Сметанник',
        nameRu: 'Сметанник',
        nameKy: 'Каймак торт',
        description: 'Нежный торт на основе сметаны',
        descriptionRu: 'Нежный торт на основе сметаны',
        descriptionKy: 'Каймак негизиндеги назик торт',
        price: 950,
        images: ['https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=400'],
        ingredients: 'Сметана, мука, сахар, яйца, ванилин',
        weight: 900,
        calories: 290,
        categoryId: IDS.CAT_CAKES,
        sortOrder: 5,
      },
    }),
    prisma.product.upsert({
      where: { id: IDS.PROD_BIRD_MILK },
      update: {},
      create: {
        id: IDS.PROD_BIRD_MILK,
        name: 'Птичье молоко',
        nameRu: 'Птичье молоко',
        nameKy: 'Куш сүтү',
        description: 'Воздушное суфле в шоколадной глазури',
        descriptionRu: 'Воздушное суфле в шоколадной глазури',
        descriptionKy: 'Шоколад глазурь ичиндеги аба суфле',
        price: 1250,
        images: ['https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=400'],
        ingredients: 'Шоколад, желатин, сливки, сахар, яйца',
        weight: 800,
        calories: 310,
        categoryId: IDS.CAT_CAKES,
        isNew: true,
        sortOrder: 6,
      },
    }),
  ]);

  // Create products - Pastries
  await Promise.all([
    prisma.product.upsert({
      where: { id: IDS.PROD_TIRAMISU },
      update: {},
      create: {
        id: IDS.PROD_TIRAMISU,
        name: 'Тирамису',
        nameRu: 'Тирамису',
        nameKy: 'Тирамису',
        description: 'Итальянский десерт с маскарпоне и кофе',
        descriptionRu: 'Итальянский десерт с маскарпоне и кофе',
        descriptionKy: 'Маскарпоне жана кофе менен италиялык десерт',
        price: 280,
        images: ['https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400'],
        ingredients: 'Маскарпоне, кофе, печенье савоярди, какао',
        weight: 150,
        calories: 280,
        categoryId: IDS.CAT_PASTRIES,
        isBestseller: true,
        sortOrder: 1,
      },
    }),
    prisma.product.upsert({
      where: { id: IDS.PROD_CHEESECAKE },
      update: {},
      create: {
        id: IDS.PROD_CHEESECAKE,
        name: 'Чизкейк Нью-Йорк',
        nameRu: 'Чизкейк Нью-Йорк',
        nameKy: 'Нью-Йорк чизкейк',
        description: 'Классический чизкейк на песочной основе',
        descriptionRu: 'Классический чизкейк на песочной основе',
        descriptionKy: 'Кумдуу негизде классикалык чизкейк',
        price: 320,
        images: ['https://images.unsplash.com/photo-1524351199678-941a58a3df50?w=400'],
        ingredients: 'Сливочный сыр, сахар, яйца, сливки, печенье',
        weight: 160,
        calories: 320,
        categoryId: IDS.CAT_PASTRIES,
        sortOrder: 2,
      },
    }),
    prisma.product.upsert({
      where: { id: IDS.PROD_PROFITEROLE },
      update: {},
      create: {
        id: IDS.PROD_PROFITEROLE,
        name: 'Профитроли (5 шт)',
        nameRu: 'Профитроли (5 шт)',
        nameKy: 'Профитролдор (5 даана)',
        description: 'Заварные шарики с кремом и шоколадом',
        descriptionRu: 'Заварные шарики с кремом и шоколадом',
        descriptionKy: 'Крем жана шоколад менен заварной шарлар',
        price: 250,
        images: ['https://images.unsplash.com/photo-1509365465985-25d11c17e812?w=400'],
        ingredients: 'Мука, масло, яйца, сливки, шоколад',
        weight: 180,
        calories: 290,
        categoryId: IDS.CAT_PASTRIES,
        isNew: true,
        sortOrder: 3,
      },
    }),
    prisma.product.upsert({
      where: { id: IDS.PROD_PANNA_COTTA },
      update: {},
      create: {
        id: IDS.PROD_PANNA_COTTA,
        name: 'Панна котта',
        nameRu: 'Панна котта',
        nameKy: 'Панна котта',
        description: 'Итальянский сливочный десерт с ягодным соусом',
        descriptionRu: 'Итальянский сливочный десерт с ягодным соусом',
        descriptionKy: 'Жемиш соусу менен италиялык каймак десерт',
        price: 220,
        images: ['https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400'],
        ingredients: 'Сливки, сахар, желатин, ваниль, ягоды',
        weight: 140,
        calories: 250,
        categoryId: IDS.CAT_PASTRIES,
        sortOrder: 4,
      },
    }),
    prisma.product.upsert({
      where: { id: IDS.PROD_BROWNIE },
      update: {},
      create: {
        id: IDS.PROD_BROWNIE,
        name: 'Брауни',
        nameRu: 'Брауни',
        nameKy: 'Брауни',
        description: 'Шоколадный брауни с грецким орехом',
        descriptionRu: 'Шоколадный брауни с грецким орехом',
        descriptionKy: 'Грек жаңгагы менен шоколад брауни',
        price: 180,
        images: ['https://images.unsplash.com/photo-1564355808539-22fda35bed7e?w=400'],
        ingredients: 'Шоколад, масло, мука, яйца, грецкий орех',
        weight: 100,
        calories: 350,
        categoryId: IDS.CAT_PASTRIES,
        isBestseller: true,
        sortOrder: 5,
      },
    }),
  ]);

  // Create products - Cookies
  await Promise.all([
    prisma.product.upsert({
      where: { id: IDS.PROD_MACARON },
      update: {},
      create: {
        id: IDS.PROD_MACARON,
        name: 'Макарон (набор 6 шт)',
        nameRu: 'Макарон (набор 6 шт)',
        nameKy: 'Макарон (6 даана)',
        description: 'Французские миндальные пирожные, ассорти вкусов',
        descriptionRu: 'Французские миндальные пирожные, ассорти вкусов',
        descriptionKy: 'Ар кандай даамдагы француз бадам пирожныйлары',
        price: 480,
        images: ['https://images.unsplash.com/photo-1569864358642-9d1684040f43?w=400'],
        ingredients: 'Миндальная мука, сахар, белок, начинки',
        weight: 120,
        calories: 180,
        categoryId: IDS.CAT_COOKIES,
        isNew: true,
        sortOrder: 1,
      },
    }),
    prisma.product.upsert({
      where: { id: IDS.PROD_OATMEAL },
      update: {},
      create: {
        id: IDS.PROD_OATMEAL,
        name: 'Овсяное печенье (5 шт)',
        nameRu: 'Овсяное печенье (5 шт)',
        nameKy: 'Сулу печенье (5 даана)',
        description: 'Домашнее овсяное печенье с изюмом',
        descriptionRu: 'Домашнее овсяное печенье с изюмом',
        descriptionKy: 'Мейиз менен үйдө жасалган сулу печенье',
        price: 150,
        images: ['https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400'],
        ingredients: 'Овсяные хлопья, мука, масло, сахар, изюм',
        weight: 200,
        calories: 220,
        categoryId: IDS.CAT_COOKIES,
        sortOrder: 2,
      },
    }),
    prisma.product.upsert({
      where: { id: IDS.PROD_CHOCOLATE_COOKIE },
      update: {},
      create: {
        id: IDS.PROD_CHOCOLATE_COOKIE,
        name: 'Шоколадное печенье (5 шт)',
        nameRu: 'Шоколадное печенье (5 шт)',
        nameKy: 'Шоколад печенье (5 даана)',
        description: 'Мягкое печенье с кусочками шоколада',
        descriptionRu: 'Мягкое печенье с кусочками шоколада',
        descriptionKy: 'Шоколад бөлүкчөлөрү менен жумшак печенье',
        price: 180,
        images: ['https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=400'],
        ingredients: 'Мука, масло, сахар, шоколад, яйца',
        weight: 200,
        calories: 280,
        categoryId: IDS.CAT_COOKIES,
        isBestseller: true,
        sortOrder: 3,
      },
    }),
    prisma.product.upsert({
      where: { id: IDS.PROD_SHORTBREAD },
      update: {},
      create: {
        id: IDS.PROD_SHORTBREAD,
        name: 'Песочное печенье (8 шт)',
        nameRu: 'Песочное печенье (8 шт)',
        nameKy: 'Кумдуу печенье (8 даана)',
        description: 'Рассыпчатое песочное печенье',
        descriptionRu: 'Рассыпчатое песочное печенье',
        descriptionKy: 'Ыдыраган кумдуу печенье',
        price: 120,
        images: ['https://images.unsplash.com/photo-1548365328-8c6db3220e4c?w=400'],
        ingredients: 'Мука, масло, сахар, яйца, ваниль',
        weight: 250,
        calories: 200,
        categoryId: IDS.CAT_COOKIES,
        sortOrder: 4,
      },
    }),
  ]);

  // Create products - Eclairs
  await Promise.all([
    prisma.product.upsert({
      where: { id: IDS.PROD_ECLAIR_CHOCO },
      update: {},
      create: {
        id: IDS.PROD_ECLAIR_CHOCO,
        name: 'Эклер шоколадный',
        nameRu: 'Эклер шоколадный',
        nameKy: 'Шоколад эклер',
        description: 'Эклер с шоколадным кремом и глазурью',
        descriptionRu: 'Эклер с шоколадным кремом и глазурью',
        descriptionKy: 'Шоколад крем жана глазурь менен эклер',
        price: 150,
        images: ['https://images.unsplash.com/photo-1525059337994-75a0c2cc5fe0?w=400'],
        ingredients: 'Мука, масло, яйца, шоколад, сливки',
        weight: 80,
        calories: 220,
        categoryId: IDS.CAT_ECLAIRS,
        isBestseller: true,
        sortOrder: 1,
      },
    }),
    prisma.product.upsert({
      where: { id: IDS.PROD_ECLAIR_VANILLA },
      update: {},
      create: {
        id: IDS.PROD_ECLAIR_VANILLA,
        name: 'Эклер ванильный',
        nameRu: 'Эклер ванильный',
        nameKy: 'Ванилдүү эклер',
        description: 'Эклер с нежным ванильным кремом',
        descriptionRu: 'Эклер с нежным ванильным кремом',
        descriptionKy: 'Назик ваниль крем менен эклер',
        price: 140,
        images: ['https://images.unsplash.com/photo-1603532648955-039310d9ed75?w=400'],
        ingredients: 'Мука, масло, яйца, ваниль, сливки',
        weight: 80,
        calories: 200,
        categoryId: IDS.CAT_ECLAIRS,
        sortOrder: 2,
      },
    }),
    prisma.product.upsert({
      where: { id: IDS.PROD_ECLAIR_CARAMEL },
      update: {},
      create: {
        id: IDS.PROD_ECLAIR_CARAMEL,
        name: 'Эклер карамельный',
        nameRu: 'Эклер карамельный',
        nameKy: 'Карамел эклер',
        description: 'Эклер с солёной карамелью',
        descriptionRu: 'Эклер с солёной карамелью',
        descriptionKy: 'Туздуу карамел менен эклер',
        price: 160,
        images: ['https://images.unsplash.com/photo-1550617931-e17a7b70dce2?w=400'],
        ingredients: 'Мука, масло, яйца, карамель, морская соль',
        weight: 85,
        calories: 230,
        categoryId: IDS.CAT_ECLAIRS,
        isNew: true,
        sortOrder: 3,
      },
    }),
    prisma.product.upsert({
      where: { id: IDS.PROD_ECLAIR_PISTACHIO },
      update: {},
      create: {
        id: IDS.PROD_ECLAIR_PISTACHIO,
        name: 'Эклер фисташковый',
        nameRu: 'Эклер фисташковый',
        nameKy: 'Писте эклер',
        description: 'Эклер с фисташковым кремом',
        descriptionRu: 'Эклер с фисташковым кремом',
        descriptionKy: 'Писте крем менен эклер',
        price: 180,
        images: ['https://images.unsplash.com/photo-1612203985729-70726954388c?w=400'],
        ingredients: 'Мука, масло, яйца, фисташки, сливки',
        weight: 85,
        calories: 240,
        categoryId: IDS.CAT_ECLAIRS,
        sortOrder: 4,
      },
    }),
  ]);

  // Create products - Drinks
  await Promise.all([
    prisma.product.upsert({
      where: { id: IDS.PROD_LATTE },
      update: {},
      create: {
        id: IDS.PROD_LATTE,
        name: 'Латте',
        nameRu: 'Латте',
        nameKy: 'Латте',
        description: 'Классический латте на натуральном молоке',
        descriptionRu: 'Классический латте на натуральном молоке',
        descriptionKy: 'Табигый сүт менен классикалык латте',
        price: 180,
        images: ['https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400'],
        ingredients: 'Эспрессо, молоко',
        weight: 350,
        calories: 150,
        categoryId: IDS.CAT_DRINKS,
        sortOrder: 1,
      },
    }),
    prisma.product.upsert({
      where: { id: IDS.PROD_CAPPUCCINO },
      update: {},
      create: {
        id: IDS.PROD_CAPPUCCINO,
        name: 'Капучино',
        nameRu: 'Капучино',
        nameKy: 'Капучино',
        description: 'Эспрессо с нежной молочной пенкой',
        descriptionRu: 'Эспрессо с нежной молочной пенкой',
        descriptionKy: 'Назик сүт көбүгү менен эспрессо',
        price: 160,
        images: ['https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=400'],
        ingredients: 'Эспрессо, молоко',
        weight: 300,
        calories: 120,
        categoryId: IDS.CAT_DRINKS,
        isBestseller: true,
        sortOrder: 2,
      },
    }),
    prisma.product.upsert({
      where: { id: IDS.PROD_HOT_CHOCOLATE },
      update: {},
      create: {
        id: IDS.PROD_HOT_CHOCOLATE,
        name: 'Горячий шоколад',
        nameRu: 'Горячий шоколад',
        nameKy: 'Ысык шоколад',
        description: 'Густой горячий шоколад из бельгийского шоколада',
        descriptionRu: 'Густой горячий шоколад из бельгийского шоколада',
        descriptionKy: 'Белгия шоколадынан коюу ысык шоколад',
        price: 200,
        images: ['https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=400'],
        ingredients: 'Молоко, бельгийский шоколад, сахар, сливки',
        weight: 300,
        calories: 280,
        categoryId: IDS.CAT_DRINKS,
        sortOrder: 3,
      },
    }),
    prisma.product.upsert({
      where: { id: IDS.PROD_TEA },
      update: {},
      create: {
        id: IDS.PROD_TEA,
        name: 'Чай (чайник)',
        nameRu: 'Чай (чайник)',
        nameKy: 'Чай (чайнек)',
        description: 'Чёрный или зелёный чай на выбор',
        descriptionRu: 'Чёрный или зелёный чай на выбор',
        descriptionKy: 'Кара же жашыл чай тандоо боюнча',
        price: 120,
        images: ['https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400'],
        ingredients: 'Чай листовой',
        weight: 400,
        calories: 5,
        categoryId: IDS.CAT_DRINKS,
        sortOrder: 4,
      },
    }),
    prisma.product.upsert({
      where: { id: IDS.PROD_LEMONADE },
      update: {},
      create: {
        id: IDS.PROD_LEMONADE,
        name: 'Лимонад домашний',
        nameRu: 'Лимонад домашний',
        nameKy: 'Үй лимонады',
        description: 'Освежающий лимонад с мятой',
        descriptionRu: 'Освежающий лимонад с мятой',
        descriptionKy: 'Жалбыз менен сергитүүчү лимонад',
        price: 140,
        images: ['https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=400'],
        ingredients: 'Лимон, сахар, мята, вода',
        weight: 400,
        calories: 80,
        categoryId: IDS.CAT_DRINKS,
        isNew: true,
        sortOrder: 5,
      },
    }),
  ]);

  // Create products - Ice Cream
  await Promise.all([
    prisma.product.upsert({
      where: { id: IDS.PROD_ICE_VANILLA },
      update: {},
      create: {
        id: IDS.PROD_ICE_VANILLA,
        name: 'Мороженое ванильное',
        nameRu: 'Мороженое ванильное',
        nameKy: 'Ванилдүү балмуздак',
        description: 'Домашнее ванильное мороженое (2 шарика)',
        descriptionRu: 'Домашнее ванильное мороженое (2 шарика)',
        descriptionKy: 'Үйдө жасалган ванилдүү балмуздак (2 шарик)',
        price: 150,
        images: ['https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=400'],
        ingredients: 'Сливки, молоко, сахар, желтки, ваниль',
        weight: 120,
        calories: 200,
        categoryId: IDS.CAT_ICE_CREAM,
        sortOrder: 1,
      },
    }),
    prisma.product.upsert({
      where: { id: IDS.PROD_ICE_CHOCOLATE },
      update: {},
      create: {
        id: IDS.PROD_ICE_CHOCOLATE,
        name: 'Мороженое шоколадное',
        nameRu: 'Мороженое шоколадное',
        nameKy: 'Шоколаддуу балмуздак',
        description: 'Насыщенное шоколадное мороженое (2 шарика)',
        descriptionRu: 'Насыщенное шоколадное мороженое (2 шарика)',
        descriptionKy: 'Каныккан шоколаддуу балмуздак (2 шарик)',
        price: 160,
        images: ['https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400'],
        ingredients: 'Сливки, молоко, шоколад, сахар, какао',
        weight: 120,
        calories: 220,
        categoryId: IDS.CAT_ICE_CREAM,
        isBestseller: true,
        sortOrder: 2,
      },
    }),
    prisma.product.upsert({
      where: { id: IDS.PROD_ICE_STRAWBERRY },
      update: {},
      create: {
        id: IDS.PROD_ICE_STRAWBERRY,
        name: 'Мороженое клубничное',
        nameRu: 'Мороженое клубничное',
        nameKy: 'Кулпунайлуу балмуздак',
        description: 'Мороженое из свежей клубники (2 шарика)',
        descriptionRu: 'Мороженое из свежей клубники (2 шарика)',
        descriptionKy: 'Жаңы кулпунайдан балмуздак (2 шарик)',
        price: 170,
        images: ['https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=400'],
        ingredients: 'Сливки, молоко, клубника, сахар',
        weight: 120,
        calories: 190,
        categoryId: IDS.CAT_ICE_CREAM,
        isNew: true,
        sortOrder: 3,
      },
    }),
    prisma.product.upsert({
      where: { id: IDS.PROD_ICE_PISTACHIO },
      update: {},
      create: {
        id: IDS.PROD_ICE_PISTACHIO,
        name: 'Мороженое фисташковое',
        nameRu: 'Мороженое фисташковое',
        nameKy: 'Пистелүү балмуздак',
        description: 'Мороженое с натуральными фисташками (2 шарика)',
        descriptionRu: 'Мороженое с натуральными фисташками (2 шарика)',
        descriptionKy: 'Табигый писте менен балмуздак (2 шарик)',
        price: 190,
        images: ['https://images.unsplash.com/photo-1560008581-09826d1de69e?w=400'],
        ingredients: 'Сливки, молоко, фисташки, сахар',
        weight: 120,
        calories: 210,
        categoryId: IDS.CAT_ICE_CREAM,
        sortOrder: 4,
      },
    }),
  ]);

  console.log('Products created: 28');

  // Create stores
  await Promise.all([
    prisma.store.upsert({
      where: { id: IDS.STORE_MAIN },
      update: {},
      create: {
        id: IDS.STORE_MAIN,
        name: 'Ширин - Центр',
        nameRu: 'Ширин - Центр',
        nameKy: 'Ширин - Борбор',
        address: 'ул. Киевская, 77',
        addressRu: 'ул. Киевская, 77',
        addressKy: 'Киев көчөсү, 77',
        latitude: 42.8746,
        longitude: 74.5698,
        phone: '+996 312 901 234',
        workHours: '08:00 - 22:00',
        image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=600',
      },
    }),
    prisma.store.upsert({
      where: { id: IDS.STORE_SOUTH },
      update: {},
      create: {
        id: IDS.STORE_SOUTH,
        name: 'Ширин - Юг',
        nameRu: 'Ширин - Юг',
        nameKy: 'Ширин - Түштүк',
        address: 'ул. Ахунбаева, 120',
        addressRu: 'ул. Ахунбаева, 120',
        addressKy: 'Ахунбаев көчөсү, 120',
        latitude: 42.8456,
        longitude: 74.5912,
        phone: '+996 312 902 345',
        workHours: '09:00 - 21:00',
        image: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=600',
      },
    }),
    prisma.store.upsert({
      where: { id: IDS.STORE_WEST },
      update: {},
      create: {
        id: IDS.STORE_WEST,
        name: 'Ширин - Запад',
        nameRu: 'Ширин - Запад',
        nameKy: 'Ширин - Батыш',
        address: 'ул. Жибек Жолу, 380',
        addressRu: 'ул. Жибек Жолу, 380',
        addressKy: 'Жибек Жолу көчөсү, 380',
        latitude: 42.8781,
        longitude: 74.5432,
        phone: '+996 312 903 456',
        workHours: '09:00 - 21:00',
        image: 'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=600',
      },
    }),
  ]);
  console.log('Stores created: 3');

  // Create promotions
  const now = new Date();
  const oneMonthLater = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);
  const twoWeeksLater = new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000);

  await Promise.all([
    prisma.promotion.upsert({
      where: { id: IDS.PROMO_WELCOME },
      update: {},
      create: {
        id: IDS.PROMO_WELCOME,
        title: 'Добро пожаловать!',
        titleRu: 'Добро пожаловать!',
        titleKy: 'Кош келиңиз!',
        description: 'Скидка 15% на первый заказ для новых клиентов',
        descriptionRu: 'Скидка 15% на первый заказ для новых клиентов',
        descriptionKy: 'Жаңы кардарлар үчүн биринчи заказга 15% арзандатуу',
        image: 'https://images.unsplash.com/photo-1558301211-0d8c8ddee6ec?w=600',
        type: 'DISCOUNT',
        discountPercent: 15,
        startDate: now,
        endDate: oneMonthLater,
        sortOrder: 1,
      },
    }),
    prisma.promotion.upsert({
      where: { id: IDS.PROMO_CASHBACK },
      update: {},
      create: {
        id: IDS.PROMO_CASHBACK,
        title: 'Двойной кешбэк',
        titleRu: 'Двойной кешбэк',
        titleKy: 'Кош кешбэк',
        description: 'Получите 10% кешбэк баллами на заказы от 2000 сом',
        descriptionRu: 'Получите 10% кешбэк баллами на заказы от 2000 сом',
        descriptionKy: '2000 сомдон ашкан заказдарга 10% кешбэк упай алыңыз',
        image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600',
        type: 'CASHBACK',
        cashbackPercent: 10,
        minOrderAmount: 2000,
        startDate: now,
        endDate: oneMonthLater,
        sortOrder: 2,
      },
    }),
    prisma.promotion.upsert({
      where: { id: IDS.PROMO_COMBO },
      update: {},
      create: {
        id: IDS.PROMO_COMBO,
        title: 'Комбо: Торт + Кофе',
        titleRu: 'Комбо: Торт + Кофе',
        titleKy: 'Комбо: Торт + Кофе',
        description: 'Закажите любой торт и получите капучино в подарок!',
        descriptionRu: 'Закажите любой торт и получите капучино в подарок!',
        descriptionKy: 'Каалаган тортко буйрутма бериңиз жана белекке капучино алыңыз!',
        image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600',
        type: 'COMBO',
        startDate: now,
        endDate: twoWeeksLater,
        sortOrder: 3,
      },
    }),
  ]);
  console.log('Promotions created: 3');

  // Create raffle
  await prisma.raffle.upsert({
    where: { id: IDS.RAFFLE_CAKE },
    update: {},
    create: {
      id: IDS.RAFFLE_CAKE,
      title: 'Розыгрыш торта!',
      titleRu: 'Розыгрыш торта!',
      titleKy: 'Торт утуштуруу!',
      description: 'Участвуйте в розыгрыше и выиграйте торт "Красный бархат" на выбор!',
      descriptionRu: 'Участвуйте в розыгрыше и выиграйте торт "Красный бархат" на выбор!',
      descriptionKy: 'Утуштурууга катышып, "Кызыл бархат" тортун утуп алыңыз!',
      image: 'https://images.unsplash.com/photo-1616541823729-00fe0aacd32c?w=600',
      prize: 'Торт "Красный бархат" (1.5 кг)',
      minPurchaseAmount: 1000,
      startDate: now,
      endDate: twoWeeksLater,
      drawDate: twoWeeksLater,
    },
  });
  console.log('Raffle created');

  console.log('\n✅ Database seeded successfully!');
  console.log('   - 6 categories');
  console.log('   - 28 products');
  console.log('   - 3 stores');
  console.log('   - 3 promotions');
  console.log('   - 1 raffle');
  console.log('   - 9 settings');
  console.log('   - 2 users (admin + test)');
}

main()
  .catch((e) => {
    console.error('Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
